### ISSUE TITLE
Begin using SemVer

### ISSUE THREAD

**Issue by ppeble** [lemurheavy/coveralls-ruby#104]
I recently updated via the [coveralls](https://github.com/lemurheavy/coveralls-ruby) gem and I ran into an issue where your most recent changes meant that you no longer supported jruby because [tins](https://github.com/flori/tins) dropped support for jruby. I request that you switch to http://semver.org/ so that upstream projects can version accordingly so that this does not occur.

Thanks!

**Comment by ptrimble** [comment]
I apologize, I realize that my original issue was too vague. I should have stated that it was specifically **jruby 1.7.x**. Here is what I was seeing in my tests:

```ruby
$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies....
Using bundler 1.12.5
Installing coderay 1.1.1
Installing rake 11.2.2
Installing json 2.0.2
Installing docile 1.1.5
Installing simplecov-html 0.10.0
Installing tins 1.11.0
Gem::InstallError: tins requires Ruby version >= 2.0.
Installing ffi 1.9.14
Installing thor 0.19.1
Using holidays 4.6.0 from source at `.`
Installing metaclass 0.0.4
Installing method_source 0.8.2
Installing power_assert 0.3.0
Installing slop 3.6.0
Installing simplecov 0.12.0
An error occurred while installing tins (1.11.0), and Bundler cannot continue.
Make sure that `gem install tins -v '1.11.0'` succeeds before bundling.
```

Here is the full Travis CI log for jruby-1.7.20: https://travis-ci.org/holidays/holidays/jobs/148640105

I also opened an issue on `tins` to make sure I am not missing something. To be clear, dropping support for an older jruby is not in and of itself bad, I was just surprised that it happened without a major version bump.

Let me know if I am missing something. Thanks!
