### ISSUE TITLE
Immediate exception when running `push` command

### ISSUE THREAD

**Issue by indirect** [lemurheavy/coveralls-ruby#105]
The `push` command expects the variable `cmds` to contain an array of commands to run. Unfortunately, [the default value is a string](https://github.com/lemurheavy/coveralls-ruby/blob/master/lib/coveralls/command.rb#L10), which means that running `coveralls push` will throw an exception unless the user has also provided a `.travis.yml` file, and that file contains an array of commands.

**Comment by indirect** [comment]
Here's the full exception backtrace:

```
$ coveralls push
bundler: failed to load command: coveralls (bin/coveralls)
NoMethodError: undefined method `each' for "bundle exec rake":String
  gems/coveralls-0.8.15/lib/coveralls/command.rb:14:in `push'
  gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  gems/coveralls-0.8.15/bin/coveralls:9:in `<top (required)>'
  bin/coveralls:23:in `load'
  bin/coveralls:23:in `<top (required)>'
```

**Comment by open-source-apoex** [comment]
I have the same problem

`/home/travis/.rvm/gems/ruby-2.3.0/gems/coveralls-0.8.15/lib/coveralls/command.rb:14:in "push": undefined method "each" for "bundle exec rake":String (NoMethodError)`

**Comment by open-source-apoex** [comment]
@lemurheavy, @indirect Opening the source code it's fairly easy to fix the problem but annoying that the coverage report cant be run on Travis CI
