### ISSUE TITLE
URGENT: Broken support for Ruby < 2.0

### ISSUE THREAD

**Issue by gildub** [lemurheavy/coveralls-ruby#107]
Please look at the dependency chain.

Effectively since term-ansicolor gems bumped from 1.3.2 to 1.4.0 there are issues (while testing on Travis with various Ruby versions for backward compatibility).

Both term-ansicolor and tins require Ruby >= 2.0 but somehow this didn't came up until now.

This seems a bit messy:
https://github.com/lemurheavy/coveralls-ruby/commit/ef89fac8a07c951f8f999bbb085f4727e8b5149d

**Comment by gildub** [comment]
fog/fog-openstack#202 deactivates coveralls but we're going to need a fix. Let's leave this one open until then.

**Comment by piotrmurach** [comment]
This is unfortunate release version of `term-ansicolor`. This library could be easily fixed by changing `term-ansicolor` requirement from `~> 1.3` to `~> 1.3.2`. Does anyone fancy PR?

For the meantime I've added the following to my Gemfile to fix the problem:
```ruby
gem 'coveralls', '~> 0.8.15'
gem 'term-ansicolor', '=1.3.2'
```

**Comment by piotrmurach** [comment]
I have submitted PR that fixes the issue - https://github.com/lemurheavy/coveralls-ruby/pull/108

**Comment by piotrmurach** [comment]
This is fixed and the issue can be closed.
