### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by gildub** [lemurheavy/coveralls-ruby#109]
Would it be possible to provide a new relase.

More specifically I'm following about https://github.com/lemurheavy/coveralls-ruby/issues/107

Thanks

**Comment by nickmerwin** [comment]
Hi @gildub that PR was included in the latest release:
https://github.com/lemurheavy/coveralls-ruby/releases/tag/v0.8.16

Thanks!

**Comment by gildub** [comment]
Hi @nickmerwin , sorry I missed that, thanks!
