### ISSUE TITLE
We are running the tests inside a docker container. Coveralls is not working 

### ISSUE THREAD

**Issue by davidvoler** [lemurheavy/coveralls-ruby#113]
We are running our rails tests inside a docker container. 
The command to run the tests is:
docker run --link mongo:localhost  -e "CI=true" -e "TRAVIS=true" ourdockerhub_account/image
We get the error that git is not found ( the container has no git installed)

What would be to run coveralls within a docker container

**Comment by blaskovicz** [comment]
Did you try installing git in your container? The code looks like it collects author, commiter, branch, commit id, commit message, and remote, and reports the information to the coveralls api...
