### ISSUE TITLE
Coveralls and Ruby 2.4

### ISSUE THREAD

**Issue by spickermann** [lemurheavy/coveralls-ruby#116]
`coveralls 0.8.19` depends on `simplecov ~> 0.12.0`.

`simplecov 0.12.0` raises deprecation warnings when running under Ruby 2.4. This was fixed today with the new `0.13.0` release.

I would appreciate if you update coveralls to depend on `simplecov ~> 0.13.0`. That would allow `coveralls` to run under Ruby 2.4 without deprecation warnings.

If you want me to submit a PR for this change, please ping me.

**Comment by tagliala** [comment]
I'm also available to submit a PR to speed up things

**Comment by tagliala** [comment]
Made this PR: #117
