### ISSUE TITLE
Project unmaintained?

### ISSUE THREAD

**Issue by JPrevost** [lemurheavy/coveralls-ruby#130]
There are several PRs that update a simple dependency and there are no comments from the maintainers of this gem.

If the maintainers no longer wish to maintain the gem, would they consider adding additional collaborators to the repo and rubygems so the community can continue to use this gem?

**Comment by vbrazo** [comment]
Exactly. It doesn't make sense to have an open source project with inactive collaborators. I'd be glad to help this repo because I am a heavy user of this gem.

**Comment by rromanchuk** [comment]
Any of you guys working on a fork i can jump on and at least have a somewhat defacto maintained fork?

**Comment by Ch4s3** [comment]
@rromanchuk I'm out of town for the next few days, but I'll fork it and add you as a collaborator.

**Comment by Ch4s3** [comment]
I invited @rromanchuk, if anyone else wants to sign on, let me know and I'll invite you to the team.

**Comment by vbrazo** [comment]
I could help as well. Feel free to add me if you believe I'd be a good fit.

**Comment by rromanchuk** [comment]
Thanks, this got lost in my inbox. On it.

**Comment by Ch4s3** [comment]
@vbrazo invited

**Comment by tagliala** [comment]
Hi,

I'm maintaining an up-to-date fork of this gem at https://github.com/tagliala/coveralls-ruby-reborn

I've changed the name and released it on RubyGems

Feel free to merge my work, there are a lot of under-the-hood changes

@vbrazo I'm also helping on Faker, you labeled and reviewed my PRs 👍

**Comment by Ch4s3** [comment]
Hey @tagliala looks like some of us had the same idea an started work on https://github.com/Coveralls-Community/coveralls-ruby. Would you be open to combining our efforts? I'd be happy to use your fork, especially if we could set it up under a group and pull in a few contributors from my fork.

**Comment by tagliala** [comment]
> Would you be open to combining our efforts? 

Yes, definitely.

Sorry but I've missed this issue, otherwise I could save you a lot of work, as yo can see I did a lot of changes.

You can merge anything you need or rebase on my fork (bad practice on the master branch, I know), rebrand the gem and add me as a contributor of `Coveralls-Community`.

Then I would be happy to dismiss my fork

**Comment by Ch4s3** [comment]
@tagliala I invited you as an admin, you have free reign to take a crack at rolling changes over(in either direction). If you'd like I can jump in and help with that. once we have all of that put together I suggest we start putting out releases and I'll go through and write some docs.

**Comment by AlexWayfer** [comment]
I'm waiting for the release of `Coveralls-Community` gem!

Thank you all for your work.

**Comment by dblock** [comment]
Is https://rubygems.org/gems/coveralls_reborn a better maintained fork?

**Comment by ioquatix** [comment]
This is weird timing. But I've been working on https://github.com/ioquatix/covered which also integrates with the coveralls backend. I feel like `coveralls` is a dead end. I'm thinking about how to make an open-source front end for analysis. But I'm pretty happy with `covered` for now, it outputs everything I could want to the terminal.
