### ISSUE TITLE
Issues with 2.6 rc2

### ISSUE THREAD

**Issue by ioquatix** [lemurheavy/coveralls-ruby#140]
https://travis-ci.com/socketry/falcon/jobs/163846367

```
    <title>Coveralls :: Oops, something went wrong (500)</title>
```

Not sure what actually failed. It seems like submitting the coverage caused some kind of problem.

**Comment by kibitan** [comment]
I also get the same issue with Ruby 2.6.0. it works with `v0.7.12` but not with latest version `0.8.22`

https://travis-ci.org/kibitan/masking/builds/473306259

```
[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
JSON::ParserError
767: unexpected token at '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" />
    <title>Coveralls :: Oops, something went wrong (500)</title>
```

**Comment by ioquatix** [comment]
This seems to have fixed itself.
