### ISSUE TITLE
Coveralls can't read json

### ISSUE THREAD

**Issue by xd009642** [lemurheavy/coveralls-ruby#147]
So using the coveralls API docs I tried to improve CI support on a tool I make. However, this seems to have caused travis to stop working. This is a sample json sent with the token changed and most of the coverage data removed. The response received is `JSON file not found or failed to parse`

```json
{  
   "repo_token":"902740602",
   "service_name":"travis-ci",
   "service_job_id":"902740602",
   "service_branch":"tarp_test",
   "source_files":[  
      {  
         "name":"src/core/colour_models.rs",
         "source_digest":"4c0a2b44de3127b065c3db22b6437297",
         "coverage":[  
            null,
            1,
            1
         ]
      }
   ]
}
```

**Comment by nickmerwin** [comment]
@xd009642 that payload needs to be the `json_file` body parameter:

https://docs.coveralls.io/api-introduction#posting-to-coveralls

**Comment by xd009642** [comment]
Ok so that was a misuse of curl while trying to debug things off the server. My code uses `json_file` and it used to work fine until I started picking up the other environment variables for different CIs to improve the experience on Jenkins. Before that I just have `repo_token`, `service_name`, `service_job_id` and the coverage data. Is there a way to see any logs on coveralls that show attempts to upload reports that failed or otherwise check the reports? 

Or any good documentation on how the optional fields like `service_branch`, `service_number`, `service_build_url`, `service_branch` and `service_pull_request` actually effect things?

**Comment by nickmerwin** [comment]
@xd009642:

> Is there a way to see any logs on coveralls that show attempts to upload reports that failed or otherwise check the reports?

Currently no but that's an interesting idea to show API request logs for a repo.

> any good documentation on how the optional fields like service_branch, service_number, service_build_url, service_branch and service_pull_request actually effect things?

Good call, we'll update our docs with more info about those.
