### ISSUE TITLE
OpenSSL::SSL::SSLError when using dist focal in Travis CI

### ISSUE THREAD

**Issue by LocoDelAssembly** [lemurheavy/coveralls-ruby#163]
When using `dist: focal` in Travis CI, I get the following error:
```
Coveralls encountered an exception:
OpenSSL::SSL::SSLError
SSL_connect returned=1 errno=0 state=error: no protocols available
```
I have prepared a demo repo and results of each distro can be seen at https://travis-ci.org/github/LocoDelAssembly/coveralls

NOTE: Normally this failure won't cause the build to fail, I added a negated `grep` to search for 'OpenSSL::SSL::SSLError' to force failure to better visualize which distros are having this problem.

Repo at https://github.com/LocoDelAssembly/coveralls

What can be done to fix this?

Thanks

**Comment by DanMegaGamer** [comment]
@LocoDelAssembly I've been having the same issue but in Heroku's CI using their stack running ubuntu 20.

It seems to be down to the way SSL is handled in the gem.

There's a second coveralls gem that's more actively maintained and that solved my issue.

https://github.com/tagliala/coveralls-ruby-reborn

**Comment by woto** [comment]
Was the same issue in github actions:

![image](https://user-images.githubusercontent.com/146704/108989035-37ef2400-76a6-11eb-97fe-25c514633dbf.png)
 
Replacing gem with coveralls_reborn helped. Thanks!

**Comment by leandromoreira** [comment]
I'm facing this issue again https://github.com/leandromoreira/redlock-rb/actions/runs/5160916661/jobs/9297795798?pr=133


[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
OpenSSL::SSL::SSLError
SSL_connect returned=1 errno=0 peeraddr=104.26.4.137:443 state=error: no protocols available
