### ISSUE TITLE
Bundler resolves dependencies infinitely when trying to install

### ISSUE THREAD

**Issue by Aaron1011** [lemurheavy/coveralls-ruby#37]
I've added covealls to my Gemfile, but when I run 'bundle install', it tries to resole dependencies infinitely. See [this Travis CI build](https://travis-ci.org/travis-ci/dpl/jobs/13734986).

**Comment by ajm188** [comment]
[This comment](https://github.com/travis-ci/dpl/pull/67#issuecomment-29166592) suggests the underlying issue was resolved. Not sure if there's anything left to do on coveralls-ruby for this.

**Comment by pboling** [comment]
Bundler has changed significantly since this issue was created.  This issue should be closed.

**Comment by Aaron1011** [comment]
Four years later, this issue finally comes to a close :smile:
