### ISSUE TITLE
Circle CI w/ Parallel Tests

### ISSUE THREAD

**Issue by jwg2s** [lemurheavy/coveralls-ruby#53]
We've got our test suite running on Circle CI w/ 8 parallel containers.  Is there any way to merge the results across containers?  I see the documentation about merging test suite results, but that seems to be for one container running a single instance of your test suite, correct?

If not, is there some clarified documentation to get Coveralls set up out of the box with Circle CI parallelism?

That would be great!

**Comment by nickmerwin** [comment]
Hi guys this is ready to go!

Here are the preliminary docs for it:
https://coveralls.zendesk.com/hc/en-us/articles/203484329

**Comment by darbyw** [comment]
@nickmerwin you have no idea how happy I am to see this - can't wait to try it out, thanks!

**Comment by nickmerwin** [comment]
@darbyw great! Please let me know how it goes.

Cheers!
