### ISSUE TITLE
Coveralls is looking into gem dependencies' code and reports they're not covered...

### ISSUE THREAD

**Issue by dmagliola** [lemurheavy/coveralls-ruby#70]
I've made a small gem ([SmsSafe](https://github.com/dmagliola/sms_safe)), and it currently has 100% code coverage (according to SimpleCov).

However, according to Coveralls, it only has 41% coverage ([report here](https://coveralls.io/r/dmagliola/sms_safe?branch=master)).

The reason for that difference seems to be that coveralls is taking the code from my gem's dependencies as part of my code, and complaining that those aren't covered...

I haven't seen it do this in any other gems I've looked into, and I haven't seen any special coveralls configuration in those gems' codebases...

The way I'm calling coveralls is by having this in my Rakefile:

```
require 'coveralls/rake/task'
Coveralls::RakeTask.new
task :test_with_coveralls => ["test", "coveralls:push"]
```

and by having Travis evecute "test_with_coveralls":

```
script: bundle exec rake test_with_coveralls
```

Which is the right way of adding it [according to their docs](https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails)

Any ideas why this might be happening?

**Comment by kknd113** [comment]
This is what I am actually looking for (look into gem's dependencies and show coverage on them)
