### ISSUE TITLE
#:nocov: stopped working when upgrading to Ruby 2.2.0

### ISSUE THREAD

**Issue by RickCarlino** [lemurheavy/coveralls-ruby#74]
I work on an OpenSource Ruby project that was ignoring some lines of code with the `#:nocov:` comment.

In a recent pull request, it stopped working. This issue coincides with an upgrade to Ruby 2.2.0

https://coveralls.io/files/443620870

Please let me know if there is any other information you need.

**Comment by opahk** [comment]
We see the same issue in one of our private repos. :nocov: marked areas are counted towards coverage % even though they shouldn't. This gives false results and differs from the way simplecov behaves. However, it does not appear to relate to ruby 2.2 in our case. We see this in both 2.2 and 2.1. Any feedback would be highly appreciated.

**Comment by jusjmkim** [comment]
I'm having no troubles with version 2.2.1, but I get a seg fault with version 2.2.2.

**Comment by erwanlr** [comment]
Same issue over here with ruby 2.1.0 to 2.2.2: https://coveralls.io/builds/3337003

**Comment by jusjmkim** [comment]
Reinstalling RVM solved my bug at least. I think it was more of a bug with RVM, but I'm not sure.

**Comment by dmagliola** [comment]
I have this problem too, in Ruby 2.1.5

**Comment by nickmerwin** [comment]
Hi all, this is added in the latest gem release:
https://github.com/lemurheavy/coveralls-ruby/releases/tag/v0.8.4

Cheers!
