### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by gravis** [lemurheavy/coveralls-ruby#75]
The latest version is 0.7.8, and neither the changelog file nor the gh releases are explaining the changes.
Could you please at least keep one updated?
Thanks :)
/cc @olivierlacan

**Comment by nickmerwin** [comment]
Good call @gravis, I'll include details in the GH releases from now on like this one:
https://github.com/lemurheavy/coveralls-ruby/releases/tag/v0.7.9

**Comment by czak** [comment]
Any chance to get some info on the latest releases? `v0.8.13` - `v0.8.15` are tagged but there is no changelog info to be found. Thanks!
