### ISSUE TITLE
Parallel coverage isn't working with CircleCI

### ISSUE THREAD

**Issue by dankohn** [lemurheavy/coveralls-ruby#77]
I was excited to try #53 but it's not working for me yet. I have the following in my circle.yml:
```yml
  post:
    - bundle exec rake coveralls:push:
        parallel: true
```
This produces 4 outputs:
```
$ bundle exec rake coveralls:push
[Coveralls] Submitting with config:
{"environment":{"pwd":"/home/ubuntu/chewy","rails_root":"/home/ubuntu/chewy","simplecov_root":"/home/ubuntu/chewy","gem_version":"0.7.9","circleci_build_num":"2939","branch":"dan-circle-parallelism-323","commit_sha":"ee2721c7765f8fc1d83d36adc51c0c1954171cbe"},"git":{"head":{"id":"ee2721c7765f8fc1d83d36adc51c0c1954171cbe","author_name":"Dan Kohn","author_email":"dan@dankohn.com","committer_name":"Dan Kohn","committer_email":"dan@dankohn.com","message":"Use correct coveralls"},"branch":"dan-circle-parallelism-323","remotes":[{"name":"origin","url":"git@github.com:spreemo/chewy.git"}]},"repo_token": "[secure]","service_name":"circleci","service_number":"2939","service_pull_request":null,"parallel":true,"service_job_number":"0"}
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #2939.1
[Coveralls] https://coveralls.io/jobs/4302292
Coverage is at 86.25%.
Coverage report sent to Coveralls.
Coverage report generated for rails_app_10193, rails_app_10558, rails_app_10739, rails_app_7960, rails_app_8623 to /home/ubuntu/chewy/coverage. 2458 / 2850 LOC (86.25%) covered.
```
```
$ bundle exec rake coveralls:push
[Coveralls] Submitting with config:
{"environment":{"pwd":"/home/ubuntu/chewy","rails_root":"/home/ubuntu/chewy","simplecov_root":"/home/ubuntu/chewy","gem_version":"0.7.9","circleci_build_num":"2939","branch":"dan-circle-parallelism-323","commit_sha":"ee2721c7765f8fc1d83d36adc51c0c1954171cbe"},"git":{"head":{"id":"ee2721c7765f8fc1d83d36adc51c0c1954171cbe","author_name":"Dan Kohn","author_email":"dan@dankohn.com","committer_name":"Dan Kohn","committer_email":"dan@dankohn.com","message":"Use correct coveralls"},"branch":"dan-circle-parallelism-323","remotes":[{"name":"origin","url":"git@github.com:spreemo/chewy.git"}]},"repo_token": "[secure]","service_name":"circleci","service_number":"2939","service_pull_request":null,"parallel":true,"service_job_number":"1"}
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #2939.1
[Coveralls] https://coveralls.io/jobs/4302293
Coverage is at 86.53%.
Coverage report sent to Coveralls.
Coverage report generated for rails_app_10054, rails_app_10419, rails_app_10941, rails_app_7972, rails_app_8633 to /home/ubuntu/chewy/coverage. 2408 / 2783 LOC (86.53%) covered.
```
(and two more like that).

But on https://coveralls.io/r/spreemo/chewy I'm seeing 4 entries for build #2939, rather than seeing them aggregated. I'm open to other configurations, but using both RSpec and Cucumber tests, and I use simplecov HTML output. So, the rake task seemed like the simplest way to invoke coveralls.

My `.simplecov` is:
```ruby
unless ENV['NO_COVERAGE']
  require 'English'
  SimpleCov.start 'rails' do
    command_name "rails_app_#{$PROCESS_ID}"
    merge_timeout 1200
    add_group 'ActiveAdmin', 'app/activeadmin'
    add_group 'Validators', 'app/validators'
    add_filter '/config/'
    add_filter '/features/'
    add_filter '/lib/assets'
    add_filter '/lib/tasks'
    add_filter '/spec/'
    add_filter '/vendor/'
  end
end
```

**Comment by nickmerwin** [comment]
Hi @dankohn you no longer need to use the coveralls:push rake task.

You should also add ```COVERALLS_PARALLEL=true``` to your build environment and set up the webhook for https://coveralls.io/webhook?repo_token=(your repo token)

Thanks!

**Comment by dankohn** [comment]
Thanks for the quick response. But I don't understand how the simplecov JSON gets from the 4 CircleCI build servers to Coveralls.io if I don't run a rake task. How does a webhook get the simplecov results? Do I need to do wear_merged! ?

**Comment by nickmerwin** [comment]
The Coveralls gem will post the coverage data to our API after every run if you use ```Coveralls.wear!``` instead of ```Coveralls.wear_merged!```. When ```COVERALLS_PARALLEL=true``` is set, the build won't be considered "done" on our side until our webhook is hit -- only then will overall coverage be calculated, notifications sent, etc.

**Comment by dankohn** [comment]
Ok, can I invoke the rake task (with parallel: true) and then invoke the webhook (once) rather than using wear_merged! ? Because I've had trouble with wear_merged! in the past that was resolved by using the rake task.

**Comment by nickmerwin** [comment]
Yeah that should work if you invoke it like so:

```bash
$ COVERALLS_PARALLEL=true bundle exec rake coveralls:push
```

**Comment by dankohn** [comment]
@nickmerwin could you please take a look at my Coveralls account. Here is the circle.yml I am using:
```yml
test:
  post:
    - COVERALLS_PARALLEL=true bundle exec rake coveralls:push:
        parallel: true
    - bundle exec pronto run -f github -c origin/master --exit-code:
        parallel: false
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=blahblah
general:
  artifacts:
    - 'coverage'
```
Coveralls is now showing 3 entries for build 2954, curiously down from the 4 entries before I added the webhook. Please feel free to reach out to me by email or phone or here if I can help debug this.

**Comment by nickmerwin** [comment]
@dankohn could you email me Circle's build output for this? (support@coveralls.io) It looks correct to me so I'm not sure why the parallel builds are getting duplicated as opposed to merged.
