### ISSUE TITLE
Test suite only runs from a git repo

### ISSUE THREAD

**Issue by orlitzky** [lemurheavy/coveralls-ruby#78]
If you attempt to run the test suite from e.g. the gem (where there's no local .git directory), the test suite throws a bunch of errors:

```
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Coveralls git error:
undefined method `gsub' for nil:NilClass
```

Running it from a git clone works as expected.

**Comment by nickmerwin** [comment]
@orlitzky are you running locally or from a CI?

**Comment by orlitzky** [comment]
Locally. Here's my lazy way to reproduce:

```
$ git clone https://github.com/lemurheavy/coveralls-ruby.git
$ cd coveralls-ruby
$ rm -rf .git
$ rake
```

**Comment by nickmerwin** [comment]
@orlitzky we have plans in the future to support arbitrary coverage data (sans git or github) but currently each build needs to be associated with a commit as though you were on a CI.
