### ISSUE TITLE
Coveralls-ruby requires ruby >= 2.0 with latest version of dependency tins

### ISSUE THREAD

**Issue by cjcolvar** [lemurheavy/coveralls-ruby#89]
Coveralls-ruby depends on term-ansicolor ~> 1.3 which in turn depends on tins ~> 1.0.  Tins 1.7.0 was released today requiring ruby >= 2.0 breaking 1.8.7 and 1.9.3 compatibility for coveralls.

**Comment by daviddavis** [comment]
:+1: 

Running into this as well.

**Comment by nickmerwin** [comment]
Thanks @cjcolvar this is fixed in the latest version `0.8.6`
