### ISSUE TITLE
Coveralls not showing coverage.

### ISSUE THREAD

**Issue by annaswims** [lemurheavy/coveralls-ruby#91]
Our travis runs look like they're submitting data to coveralls, 

````
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #15778.1
[Coveralls] https://coveralls.io/jobs/9774785
Coverage is at 63.04%.
Coverage report sent to Coveralls.
````
but our coveralls page shows

`COVERAGE REMAINED THE SAME AT ?%`

**Comment by annaswims** [comment]
Actually, I think the problem is that it takes close to 24 hours to display the data.

**Comment by kbrock** [comment]
@annaswims is this still a problem?

**Comment by annaswims** [comment]
no, it seemed to resolve itself a few days later.
