### ISSUE TITLE
warning: instance variable @track_files_glob not initialized

### ISSUE THREAD

**Issue by spickermann** [lemurheavy/coveralls-ruby#92]
I get the following warning when I running my test suite:

    /.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simplecov-0.11.1/lib/simplecov.rb:56: warning: instance variable @track_files_glob not initialized

It seems like the Coveralls gem is missing to set some configuration on the simplecov gem. The `track_files` config in question was introduced to SimpleCov in this PR: https://github.com/colszowka/simplecov/pull/422 just a few weeks ago.

**Comment by kbrock** [comment]
@spickermann this has been fixed in simplecov. They added a `defined?(@track_files_glob)` in their code

close?

**Comment by spickermann** [comment]
I just ran a test suite and the warning is gone. Thanks a lot.
